openapi: 3.0.0
info:
  title: Translation API for Learning Platform
  description: API for Urdu translation of educational content
  version: 1.0.0
servers:
  - url: https://api.yourdomain.com
    description: Production server
  - url: http://localhost:3000/api
    description: Development server

paths:
  /translate/to-urdu:
    post:
      summary: Translate content to Urdu
      description: Translate English content to Urdu with optional context
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: Content to translate to Urdu
                context:
                  type: string
                  description: Optional context for better translation accuracy
                cacheEnabled:
                  type: boolean
                  default: true
                  description: Whether to use/cache the translation
      responses:
        '200':
          description: Translation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  originalContent:
                    type: string
                    description: Original English content
                  translatedContent:
                    type: string
                    description: Urdu translation
                  language:
                    type: string
                    example: "ur"
                    description: Target language code
                  cacheId:
                    type: string
                    description: ID of cached translation if applicable
                  qualityScore:
                    type: number
                    format: float
                    minimum: 0
                    maximum: 1
                    description: Estimated quality score of translation
        '400':
          description: Invalid content format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Translation service error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /translate/cache/{cacheId}:
    get:
      summary: Get cached translation
      description: Retrieve a previously cached translation
      parameters:
        - name: cacheId
          in: path
          required: true
          schema:
            type: string
          description: ID of the cached translation
      responses:
        '200':
          description: Cached translation retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslationResponse'
        '404':
          description: Cache entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    TranslationResponse:
      type: object
      properties:
        originalContent:
          type: string
        translatedContent:
          type: string
        language:
          type: string
          example: "ur"
        cacheId:
          type: string
        createdAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time
        hitCount:
          type: integer

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: "error"
        message:
          type: string
          example: "Error description"